# Import existing Python image from Docker Hub
FROM python:3.10.0-slim-buster

# Expose the port that the app will run on
EXPOSE 8080

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r /app/requirements.txt

# Run app.py when the container launches
CMD ["python", "/app/main.py"]