# Import existing Python image from Docker Hub
FROM python:3.10.0-slim-buster

# Expose the port that the app will run on


# Set the working directory to /app


# Copy the current directory contents into the container at /app


# Install any needed packages specified in requirements.txt


# Run app.py when the container launches
CMD ["python", "/app/main.py"]